name: election_calculator
channels:
  - pytask
  - conda-forge
  - defaults
dependencies:
  - anyio=2.2.0=py39hcbf5309_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=20.1.0=py39hb82d6ee_2
  - async_generator=1.10=py_0
  - atomicwrites=1.4.0=pyh9f0ad1d_0
  - attrs=20.3.0=pyhd3deb0d_0
  - babel=2.9.0=pyhd3deb0d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - beautifulsoup4=4.9.3=pyhb0f4dca_0
  - bleach=3.3.0=pyh44b312d_0
  - brotlipy=0.7.0=py39hb82d6ee_1001
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2021.1.19=haa95532_1
  - cairo=1.16.0=hba8bd2f_1007
  - certifi=2020.12.5=py39haa95532_0
  - cffi=1.14.5=py39h0878f49_0
  - chardet=4.0.0=py39hcbf5309_1
  - click=7.1.2=pyh9f0ad1d_0
  - click-default-group=1.2.1=py_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - conda=4.9.2=py39hcbf5309_0
  - conda-build=3.21.4=py39hcbf5309_0
  - conda-package-handling=1.7.2=py39h9300fe8_0
  - coverage=5.5=py39hb82d6ee_0
  - cryptography=3.4.6=py39hd8d06c1_0
  - cycler=0.10.0=py_2
  - decorator=4.4.2=py_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - distlib=0.3.1=pyh9f0ad1d_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.2.10=h39d44d4_0
  - filelock=3.0.12=pyh9f0ad1d_0
  - fontconfig=2.13.1=h1989441_1004
  - freetype=2.10.4=h546665d_1
  - fribidi=1.0.10=h8d14728_0
  - getopt-win32=0.1=h8ffe710_0
  - gettext=0.19.8.1=h1a89ca6_1005
  - glob2=0.7=py_0
  - graphviz=2.46.1=h08d4dcb_4
  - gts=0.7.6=h7c369d9_2
  - icu=68.1=h0e60522_0
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=3.7.3=py39hcbf5309_0
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - intel-openmp=2020.3=h57928b3_311
  - ipykernel=5.5.0=py39h832f523_1
  - ipython=7.21.0=py39h832f523_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.0=py39hcbf5309_2
  - jinja2=2.11.3=pyh44b312d_0
  - jpeg=9d=h8ffe710_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter-packaging=0.7.12=pyhd8ed1ab_0
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py39hcbf5309_0
  - jupyter_server=1.4.1=py39hcbf5309_0
  - jupyterlab=3.0.10=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.3.0=pyhd8ed1ab_0
  - kiwisolver=1.3.1=py39h2e07f2f_1
  - latex-dependency-scanner=0.0.2=py_0
  - lcms2=2.12=h2a16943_0
  - libarchive=3.5.1=h8686738_1
  - libblas=3.9.0=8_mkl
  - libcblas=3.9.0=8_mkl
  - libclang=11.1.0=default_h5c34c98_0
  - libffi=3.3=h0e60522_2
  - libgd=2.3.0=heebb4dc_1
  - libglib=2.66.7=h1e62bf3_1
  - libiconv=1.16=he774522_0
  - liblapack=3.9.0=8_mkl
  - liblief=0.10.1=ha925a31_2
  - libpng=1.6.37=h1d00b33_2
  - libsodium=1.0.18=h8d14728_1
  - libtiff=4.2.0=hc10be44_0
  - libwebp=1.2.0=h57928b3_0
  - libwebp-base=1.2.0=h8ffe710_0
  - libxcb=1.13=hcd874cb_1003
  - libxml2=2.9.10=hf5bbc77_3
  - lz4-c=1.9.3=h8ffe710_0
  - lzo=2.10=he774522_1000
  - m2-msys2-runtime=2.5.0.17080.65c939c=3
  - m2-patch=2.7.5=2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py39hb82d6ee_3
  - matplotlib=3.3.4=py39hcbf5309_0
  - matplotlib-base=3.3.4=py39h581301d_0
  - menuinst=1.4.16=py39hde42818_1
  - mistune=0.8.4=py39hb82d6ee_1003
  - mkl=2020.4=hb70f87d_311
  - more-itertools=8.7.0=pyhd8ed1ab_0
  - msys2-conda-epoch=20160418=1
  - nbclassic=0.2.6=pyhd8ed1ab_0
  - nbclient=0.5.3=pyhd8ed1ab_0
  - nbconvert=6.0.7=py39hcbf5309_3
  - nbformat=5.1.2=pyhd8ed1ab_1
  - nest-asyncio=1.4.3=pyhd8ed1ab_0
  - networkx=2.5=py_0
  - notebook=6.2.0=py39hcbf5309_0
  - numpy=1.20.1=py39h6635163_0
  - olefile=0.46=pyh9f0ad1d_1
  - openssl=1.1.1j=h2bbff1b_0
  - packaging=20.9=pyh44b312d_0
  - pandas=1.2.3=py39h2e25243_0
  - pandoc=2.12=h8ffe710_0
  - pandocfilters=1.4.2=py_1
  - pango=1.42.4=hec34917_5
  - parso=0.8.1=pyhd8ed1ab_0
  - pcre=8.44=ha925a31_0
  - pickleshare=0.7.5=py_1003
  - pillow=8.1.2=py39h1a9d4f7_0
  - pip=21.0.1=pyhd8ed1ab_0
  - pixman=0.40.0=h8ffe710_0
  - pkginfo=1.7.0=pyhd8ed1ab_0
  - pluggy=0.13.1=py39hcbf5309_4
  - pony=0.7.14=pyhd8ed1ab_0
  - prometheus_client=0.9.0=pyhd3deb0d_0
  - prompt-toolkit=3.0.17=pyha770c72_0
  - psutil=5.8.0=py39hb82d6ee_1
  - pthread-stubs=0.4=hcd874cb_1001
  - py=1.10.0=pyhd3deb0d_0
  - py-lief=0.10.1=py39h6c31a18_2
  - pycosat=0.6.3=py39hb82d6ee_1006
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.8.1=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py39hcbf5309_7
  - pyqt-impl=5.12.3=py39h415ef7b_7
  - pyqt5-sip=4.19.18=py39h415ef7b_7
  - pyqtchart=5.12=py39h415ef7b_7
  - pyqtwebengine=5.12.1=py39h415ef7b_7
  - pyrsistent=0.17.3=py39hb82d6ee_2
  - pyshp=2.1.3=pyhd3eb1b0_0
  - pysocks=1.7.1=py39hcbf5309_3
  - pytask=0.0.11=py_0
  - pytask-latex=0.0.11=py_0
  - pytest=6.2.2=py39hcbf5309_0
  - pytest-cov=2.11.1=pyh44b312d_0
  - python=3.9.2=h7840368_0_cpython
  - python-dateutil=2.8.1=py_0
  - python-graphviz=0.16=pyh243d235_2
  - python-libarchive-c=2.9=py39hcbf5309_2
  - python_abi=3.9=1_cp39
  - pytz=2021.1=pyhd8ed1ab_0
  - pywin32=300=py39hb82d6ee_0
  - pywinpty=0.5.7=py39hde42818_1
  - pyyaml=5.4.1=py39hb82d6ee_0
  - pyzmq=22.0.3=py39he46f08e_1
  - qt=5.12.9=h5909a2a_4
  - requests=2.25.1=pyhd3deb0d_0
  - ripgrep=12.1.1=h301d43c_1
  - ruamel_yaml=0.15.80=py39hb82d6ee_1004
  - rxspencer=3.9.0=h8ffe710_0
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py39hcbf5309_3
  - six=1.15.0=pyh9f0ad1d_0
  - sniffio=1.2.0=py39hcbf5309_1
  - soupsieve=2.0.1=py_1
  - sqlite=3.34.0=h8ffe710_0
  - terminado=0.9.2=py39hcbf5309_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=h8ffe710_1
  - toml=0.10.2=pyhd8ed1ab_0
  - tornado=6.1=py39hb82d6ee_1
  - tqdm=4.59.0=pyhd8ed1ab_0
  - traitlets=5.0.5=py_0
  - tzdata=2021a=he74cb21_0
  - urllib3=1.26.3=pyhd8ed1ab_0
  - vc=14.2=hb210afc_4
  - virtualenv=20.0.33=py39hde42818_1
  - vs2015_runtime=14.28.29325=h5e1d092_4
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.36.2=pyhd3deb0d_0
  - win_inet_pton=1.1.0=py39hcbf5309_2
  - wincertstore=0.2=py39hcbf5309_1006
  - winpty=0.4.3=4
  - xorg-kbproto=1.0.7=hcd874cb_1002
  - xorg-libice=1.0.10=hcd874cb_0
  - xorg-libsm=1.2.3=hcd874cb_1000
  - xorg-libx11=1.6.12=h301d43c_0
  - xorg-libxau=1.0.9=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xorg-libxext=1.3.4=h301d43c_0
  - xorg-libxpm=3.5.13=h301d43c_0
  - xorg-libxt=1.1.5=h301d43c_1003
  - xorg-xextproto=7.3.0=hcd874cb_1002
  - xorg-xproto=7.0.31=hcd874cb_1007
  - xz=5.2.5=h62dcd97_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.4=h0e60522_0
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h62dcd97_1010
  - zstd=1.4.9=h6255e5f_0
  - pip:
    - alabaster==0.7.12
    - astroid==2.5.1
    - cfgv==3.2.0
    - docutils==0.16
    - identify==2.1.3
    - imagesize==1.2.0
    - isort==5.7.0
    - latexcodec==2.0.1
    - lazy-object-proxy==1.5.2
    - livereload==2.6.3
    - mccabe==0.6.1
    - nodeenv==1.5.0
    - pre-commit==2.11.1
    - pybtex==0.24.0
    - pybtex-docutils==1.0.0
    - pylint==2.7.2
    - snowballstemmer==2.1.0
    - sphinx==3.5.2
    - sphinx-autobuild==2021.3.14
    - sphinx-rtd-theme==0.5.1
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-bibtex==2.2.0
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - wrapt==1.12.1
