name: election_calculator
channels:
  - pytask
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.4=py_0
  - argon2-cffi=20.1.0=py39h2bbff1b_1
  - async_generator=1.10=pyhd3eb1b0_0
  - atomicwrites=1.4.0=py_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.9.3=pyha847dfd_0
  - bleach=3.3.0=pyhd3eb1b0_0
  - brotlipy=0.7.0=py39h2bbff1b_1003
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2021.1.19=haa95532_1
  - certifi=2020.12.5=py39haa95532_0
  - cffi=1.14.5=py39hcd4344a_0
  - chardet=4.0.0=py39haa95532_1003
  - click=7.1.2=pyhd3eb1b0_0
  - click-default-group=1.2.1=py_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - conda=4.9.2=py39haa95532_0
  - conda-build=3.21.4=py39haa95532_0
  - conda-package-handling=1.7.2=py39h8cc25b3_1
  - coverage=5.5=py39h2bbff1b_2
  - cryptography=3.4.6=py39h71e12ea_0
  - cycler=0.10.0=py39haa95532_0
  - decorator=4.4.2=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distlib=0.3.1=pyhd3eb1b0_0
  - entrypoints=0.3=py39haa95532_0
  - filelock=3.0.12=pyhd3eb1b0_1
  - freetype=2.10.4=hd328e21_0
  - geos=3.8.0=h33f27b4_0
  - glob2=0.7=pyhd3eb1b0_0
  - graphviz=2.38=hfd603c8_2
  - icu=58.2=ha925a31_3
  - idna=2.10=pyhd3eb1b0_0
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2020.2=254
  - ipykernel=5.3.4=py39h7b7c402_0
  - ipython=7.21.0=py39h832f523_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.0=py39haa95532_1
  - jinja2=2.11.3=pyhd3eb1b0_0
  - jpeg=9b=hb83a4c4_2
  - json5=0.9.5=py_0
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.7.1=py39haa95532_0
  - jupyterlab=2.2.6=py_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=1.2.0=py_0
  - kiwisolver=1.3.1=py39hd77b12b_0
  - latex-dependency-scanner=0.0.2=py_0
  - libarchive=3.4.2=h5e25573_0
  - libblas=3.9.0=8_mkl
  - libcblas=3.9.0=8_mkl
  - libiconv=1.15=h1df5818_7
  - liblapack=3.9.0=8_mkl
  - liblief=0.10.1=hd77b12b_1
  - libpng=1.6.37=h2a8f88b_0
  - libsodium=1.0.18=h62dcd97_0
  - libspatialindex=1.9.3=h33f27b4_0
  - libtiff=4.2.0=he0120a3_0
  - libxml2=2.9.10=hb89e7f3_3
  - lz4-c=1.9.3=h2bbff1b_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py39h2bbff1b_0
  - matplotlib=3.3.4=py39haa95532_0
  - matplotlib-base=3.3.4=py39h49ac443_0
  - menuinst=1.4.16=py39h2bbff1b_0
  - mistune=0.8.4=py39h2bbff1b_1000
  - mkl=2020.4=hb70f87d_311
  - more-itertools=8.7.0=pyhd3eb1b0_0
  - msys2-conda-epoch=20160418=1
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.0.7=py39haa95532_0
  - nbformat=5.1.2=pyhd3eb1b0_1
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - networkx=2.5=py_0
  - notebook=6.2.0=py39haa95532_0
  - numpy=1.20.1=py39h6635163_0
  - olefile=0.46=py_0
  - openssl=1.1.1j=h2bbff1b_0
  - packaging=20.9=pyhd3eb1b0_0
  - pandas=1.2.3=py39hf11a4ad_0
  - pandoc=2.11=h9490d1a_0
  - pandocfilters=1.4.3=py39haa95532_1
  - parso=0.8.1=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.1.2=py39h4fa10fc_0
  - pip=21.0.1=py39haa95532_0
  - pkginfo=1.7.0=py39haa95532_0
  - pluggy=0.12.0=py_0
  - pony=0.7.14=pyhd8ed1ab_0
  - prometheus_client=0.9.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.8=py_0
  - psutil=5.8.0=py39h2bbff1b_1
  - py=1.10.0=pyhd3eb1b0_0
  - py-lief=0.10.1=py39hd77b12b_1
  - pycosat=0.6.3=py39h2bbff1b_0
  - pycparser=2.20=py_2
  - pygments=2.8.1=pyhd3eb1b0_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py39hd77b12b_6
  - pyrsistent=0.17.3=py39h2bbff1b_0
  - pyshp=2.1.3=pyhd3eb1b0_0
  - pysocks=1.7.1=py39haa95532_0
  - pytask=0.0.11=py_0
  - pytask-latex=0.0.11=py_0
  - pytest=6.2.2=py39haa95532_2
  - pytest-cov=2.11.1=pyhd3eb1b0_0
  - python=3.9.2=h6244533_0
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python-graphviz=0.16=pyhd3eb1b0_1
  - python-libarchive-c=2.9=py39haa95532_0
  - python_abi=3.9=1_cp39
  - pytz=2021.1=pyhd3eb1b0_0
  - pywin32=228=py39he774522_0
  - pywinpty=0.5.7=py39haa95532_0
  - pyyaml=5.4.1=py39h2bbff1b_1
  - pyzmq=20.0.0=py39hd77b12b_1
  - qt=5.9.7=vc14h73c81de_0
  - requests=2.25.1=pyhd3eb1b0_0
  - rtree=0.9.4=py39h2eaa2aa_1
  - ruamel_yaml=0.15.80=py39hb82d6ee_1004
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=52.0.0=py39haa95532_0
  - sip=4.19.13=py39hd77b12b_0
  - six=1.15.0=py39haa95532_0
  - soupsieve=2.2=pyhd3eb1b0_0
  - sqlite=3.35.0=h2bbff1b_0
  - terminado=0.9.2=py39haa95532_0
  - testpath=0.4.4=pyhd3eb1b0_0
  - tk=8.6.10=he774522_0
  - toml=0.10.1=py_0
  - tornado=6.1=py39h2bbff1b_0
  - tqdm=4.59.0=pyhb85f177_0
  - traitlets=5.0.5=pyhd3eb1b0_0
  - tzdata=2020f=h52ac0ba_0
  - urllib3=1.26.3=pyhd3eb1b0_0
  - vc=14.2=h21ff451_1
  - virtualenv=20.4.2=py39haa95532_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py39haa95532_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=py39haa95532_0
  - wincertstore=0.2=py39h2bbff1b_0
  - winpty=0.4.3=4
  - xz=5.2.5=h62dcd97_0
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.3=ha925a31_3
  - zipp=3.4.0=pyhd3eb1b0_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.4.5=h04227a9_0
  - pip:
    - alabaster==0.7.12
    - astroid==2.5.1
    - cfgv==3.2.0
    - click-plugins==1.1.1
    - cligj==0.7.1
    - docutils==0.16
    - identify==2.1.3
    - imagesize==1.2.0
    - isort==5.7.0
    - latexcodec==2.0.1
    - lazy-object-proxy==1.5.2
    - livereload==2.6.3
    - mccabe==0.6.1
    - munch==2.5.0
    - nodeenv==1.5.0
    - pre-commit==2.11.1
    - pybtex==0.24.0
    - pybtex-docutils==1.0.0
    - pylint==2.7.2
    - pyproj==3.0.1
    - shapely==1.7.1
    - snowballstemmer==2.1.0
    - sphinx==3.5.2
    - sphinx-autobuild==2021.3.14
    - sphinx-rtd-theme==0.5.1
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-bibtex==2.2.0
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - wrapt==1.12.1
